### PR TITLE
WIP:Create sonar-cloud

### PR DESCRIPTION
**Pull request by danielt998**

### CODE REVIEW

**Comment by IdiosApps** [comment]
I don't see anything about sonar in the build logs - is this WIP or is PR ready for review?

**Comment by danielt998** [comment]
Still wip I can't figure out what's happening/why it's not giving any output etc

**Comment by IdiosApps** [comment]
switch PR to draft for now?

**Comment by IdiosApps** [comment]
We now need to set up things on the SonarCloud side :) 
https://github.com/SonarSource/sonarcloud-github-action#requirements

**Comment by IdiosApps** [comment]
Oh - we should be using SonarQube with Gradle, not Github Actions!
https://github.com/danielt998/HanziToAnki/pull/83#issuecomment-1166626652

**Pull request closed without merging**
